/**
 * Universal sample photos used as defaults across every preview surface
 * (normal-user homepage preview, photographer preview, admin form preview)
 * so the layout looks consistent BEFORE any real photos have been uploaded.
 *
 * These are the same three photos the user picked in Feb 2026 — Indian luxe
 * wedding portraits (Couple + Bride solo + Groom solo).
 */

export const DEFAULT_COUPLE_PHOTO =
  'https://images.unsplash.com/photo-1604017011826-d3b4c23f8914?w=1400&q=85&auto=format&fit=crop';

export const DEFAULT_BRIDE_PHOTO =
  'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=85&auto=format&fit=crop';

export const DEFAULT_GROOM_PHOTO =
  'https://images.unsplash.com/photo-1601471075416-8c19a6a565c5?w=1200&q=85&auto=format&fit=crop';

/** Single-photo fallback for haldi / mehendi where there's no couple shot. */
export const DEFAULT_SINGLE_PHOTO = DEFAULT_BRIDE_PHOTO;

/* Event-specific single-person previews generated by Gemini Nano Banana
   (2026-02). Served from the backend /uploads static mount. */
const BACKEND_URL = (process.env.REACT_APP_BACKEND_URL || '').replace(/\/$/, '');
export const HALDI_SINGLE_PHOTO  = `${BACKEND_URL}/uploads/themes/haldi-single.png`;
export const MEHNDI_SINGLE_PHOTO = `${BACKEND_URL}/uploads/themes/mehndi-single.png`;

/* Helper — given a normalised event name, return the best single-person
   photo to use in the rich preview. Falls back to couple photo otherwise. */
export const eventPhoto = (event) => {
  const e = String(event || '').toLowerCase();
  if (e === 'haldi') return HALDI_SINGLE_PHOTO;
  if (e === 'mehndi' || e === 'mehendi' || e === 'mehandi') return MEHNDI_SINGLE_PHOTO;
  return DEFAULT_COUPLE_PHOTO;
};

export const samplePhotos = {
  couple: DEFAULT_COUPLE_PHOTO,
  bride:  DEFAULT_BRIDE_PHOTO,
  groom:  DEFAULT_GROOM_PHOTO,
  single: DEFAULT_SINGLE_PHOTO,
  haldi:  HALDI_SINGLE_PHOTO,
  mehndi: MEHNDI_SINGLE_PHOTO,
};

export default samplePhotos;
